j = int(input())
t = int(input())
phi = 22/7
v =phi*(j*j)*t
l =2*phi*j*(j+t)
k =2*phi*j
print("Volume = %.2f" %v)
print("Luas = %.2f" %l)
print("Keliling = %.2f\n\n" %k)
j1,t1 = input().split()
j1 =float(j1)
t1 =float(t1)
phi1 = 22/7
v1 =phi1*(j1*j1)*t1
l1 =2*phi1*j1*(j1+t1)
k1 =2*phi1*j1
print("Volume = %.2f" %v1)
print("Luas = %.2f" %l1)
print("Keliling = %.2f\n\n" %k1)