a = input('Nama :')
b = input('NIM :')
c = input('Kelas Pararel :')
d = input('Tempat/Tanggal Lahir :')
e = input('Alamat :')
f = input('Hobby :')
g = input('No.HP :')


print('\n')
print('Nama : ' + a)
print('NIM : ' + b)
print('Kelas Pararel : ' + c)
print('Tempat/Tanggal Lahir : ' + d)
print('Alamat : ' + e)
print('Hobby : ' + f)
print('No. HP : ' + g)